### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by Supersak80** [Atcold/pytorch-MatchNet#1]
Hi @Atcold , can you provide the corresponding paper for this algorithm?

**Comment by Atcold** [comment]
Hahahaha! Let me first publish it, then I'll provide the link!
Moreover, the repo went private (there are several thousands more lines on my machine).

**Comment by Supersak80** [comment]
@Atcold Oh, wow, I didn't realize this is yet to be published! What is the application of MatchNet?

**Comment by Atcold** [comment]
We are trying to build a robust representation for video input data.
As it is right now there are strong fluctuations of the output of the final classifier due to natural occurring adversarial noise. We are trying to reduce its effect on our neural networks by exploiting temporal contiguity among the frames.
In short, this should be my thesis code 😉  so, most of it will stay private until I'm done.

**Comment by Atcold** [comment]
The paper is going out on Monday!
Have a look at the project website for the moment!

**Comment by Atcold** [comment]
And here is the paper https://arxiv.org/abs/1706.02735
Closing this issue now.
