### ISSUE TITLE
can not download the dataset

### ISSUE THREAD

**Issue by kikyou123** [Atcold/pytorch-MatchNet#7]
when i download the data in  https://engineering.purdue.edu/elab/eVDS/#download, 
i find 
![image](https://user-images.githubusercontent.com/19486038/30630939-28291a2a-9e15-11e7-8af4-84ae80b69c4a.png)
what is wrong with that?

**Comment by Atcold** [comment]
I believe the server is down, at Purdue, and I've moved to NYU.
Perhaps @codeAC29 or @culurciello can bring it up again?

**Comment by Atcold** [comment]
Alright, it looks like Purdue's network has been down since yesterday.
Tomorrow it should come back up. Sorry for the inconvenience.

**Comment by kikyou123** [comment]
thanks you, but i don not find e-VDS35-May17.tar in the e-VDS.
![image](https://user-images.githubusercontent.com/19486038/30898883-1745fb08-a390-11e7-8353-7019cfb69738.png)

**Comment by Atcold** [comment]
The FTP drive restored crap from two years ago.
I've just notified @codeAC29 and @culurciello about this.
Sorry once again for the inconvenience.

**Comment by Atcold** [comment]
The FTP drive have been restored.

**Comment by kikyou123** [comment]
OK, I can download the datasets. Thanks you very much!!!

**Comment by guanfuchen** [comment]
The server can not download the data, where can I get the data?

**Comment by Atcold** [comment]
@guanfuchen, to me it works fine. 你可以再試一次嗎？

**Comment by guanfuchen** [comment]
Canziani, thanks for your reply, now I can download the data from the command line. I thought the resource is lost because I can not see the data directory using the web browser.


-----原始邮件-----
发件人:"Alfredo Canziani" <notifications@github.com>
发送时间:2017-11-16 22:04:49 (星期四)
收件人: Atcold/pytorch-CortexNet <pytorch-CortexNet@noreply.github.com>
抄送: guanfuchen <guanfuchen@zju.edu.cn>, Mention <mention@noreply.github.com>
主题: Re: [Atcold/pytorch-CortexNet] can not download the dataset (#7)



@guanfuchen, to me it works fine. 你可以再試一次嗎？

**Comment by Atcold** [comment]
@guanfuchen, 太棒了！

**Comment by lrusha** [comment]
Hi, I am not able to access the dataset when I click on the link

**Comment by Atcold** [comment]
Hi @lrusha. You may want to get in touch with @culurciello.
His email address is `eculurciello` @ micron. com.

**Comment by lrusha** [comment]
Thank you.

**Comment by culurciello** [comment]
Hi, my email is culurciello @ gmail , but unfortunately we did not keep a copy of that dataset, was deleted.
